---
title: "Seminarska naloga - vizualizacija podatkov"
author: "Neža Kržan, Tom Rupnik Medjedovič"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plotly)
```

```{r include=FALSE}
#podatki = read.csv("podatki.csv", sep=';')

podatki = read.csv("podatki.csv", sep=';', na.strings = "...")

# ime stolpca Vzork.smrti --> stevilo
colnames(podatki)[5] = "stevilo"

# ime stolpca Vzrok.smrti.na.1000.prebivalcev --> stevilo1000
colnames(podatki)[6] = "stevilo1000"

podatki$VZROK.SMRTI[podatki$VZROK.SMRTI == "Bolezni obtocil (I00-I99)"] = "Bolezni obtočil (I00-I99)"

podatki$VZROK.SMRTI[podatki$VZROK.SMRTI == "Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)"] = "Poškodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)"
```

```{r include=FALSE}
df_mankajoce_vrednosti = podatki[!complete.cases(podatki), ]
df = na.omit(podatki)
```

### Delež smrti glede na vzrok po kohezijskih regijah
#### od leta 2002 do 2022

**Graf je namenjen podrobnejšemu pregledu deleža umrlih glede na vzrok po kohezijskih Regijah. Graf lahko spreminjamo glede na leta in glede na spol.**

```{r message=FALSE, warning=FALSE, include=FALSE}
mz = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
mv = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zz = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zv = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]

df = na.omit(data.frame(leto = mz$LETO,
                stevilo.v = c(mv$stevilo,zv$stevilo),
                stevilo.z = c(mz$stevilo, zz$stevilo),
                vzrok = c(mz$VZROK.SMRTI,zz$VZROK.SMRTI),
                spol = c(mz$SPOL, zz$SPOL)))
```

```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, fig.align="center"}
ui <- fluidPage(
  headerPanel(''),
  sidebarPanel(
    fluidRow(
      column(width = 6,
             selectInput("izbrano_leto1", label="Izberite leto",
                         choices = sort(unique(df$leto)), selected = 2002)),
      column(width = 6,
             selectInput("izbran_spol1", label="Izberite spol",
                         choices = c("Moški", "Ženske"), selected = "Moški"))
      ),
    # druga vrstica
    fluidRow(
      column(width = 6,
             selectInput("izbrano_leto2", label="Izberite leto",
                         choices = sort(unique(df$leto)), selected = 2002)),
      column(width = 6,
             selectInput("izbran_spol2", label="Izberite spol",
                         choices = c("Moški", "Ženske"), selected = "Moški"))
      )
    #selected = names(mtcars)[[2]]
    ),
  mainPanel(
    plotlyOutput('plot')
  )
)


server <- function(input, output) {
  
  barve1 = reactive({
    
    req(input$izbrano_leto1)
    
    if (input$izbrano_leto1 %in% c("2020","2021","2022")){
      c("#0072B2","#E69F00","#56B4E9","#009E73", "#D55E00","#000000")
    } else {
      c("#E69F00","#56B4E9","#009E73","#D55E00","#000000")
    }
    })
  
  barve2 = reactive({
    
    req(input$izbrano_leto2)
    
    if (input$izbrano_leto2 %in% c("2020","2021","2022")){
      c("#0072B2","#E69F00","#56B4E9","#009E73", "#D55E00","#000000")
    } else {
      c("#E69F00","#56B4E9","#009E73","#D55E00","#000000")
    }
    })
  
  
  data1 <- reactive({

    req(input$izbrano_leto1,input$izbran_spol1)
    
    spol_izbira = ifelse(input$izbran_spol1 == "Moški", "Moski", "Zenske")
    
    df %>% 
      select(leto, stevilo.v, stevilo.z, spol, vzrok) %>%
      filter(leto %in% input$izbrano_leto1, spol %in% spol_izbira)
    })
  
  data2 <- reactive({

    req(input$izbrano_leto2,input$izbran_spol2)
    
    spol_izbira = ifelse(input$izbran_spol2 == "Moški", "Moski", "Zenske")
    
    df %>% 
      select(leto, stevilo.v, stevilo.z, spol, vzrok) %>%
      filter(leto %in% input$izbrano_leto2, spol %in% spol_izbira)
    })
  
  
  output$plot <- renderPlotly(
    subplot(
    plot_ly(marker = list(line = list(color = 'white', width = 1), colors=barve1())) %>%
      add_pie(data = data1(), labels = ~vzrok, values = ~stevilo.z,
              name = "ZS", 
              domain = list(row = 0, column = 0)) %>% 
      add_pie(data = data1(), labels = ~vzrok, values = ~stevilo.v,
              name = "VS", 
              domain = list(row = 0, column = 1)) %>%
      layout(title = "", showlegend = F, grid=list(rows=2, columns=2),
             xaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE)),
      # druga vrstica
    p2 = plot_ly(marker = list(line = list(color = 'white', width = 1), colors=barve2())) %>%
      add_pie(data = data2(), labels = ~vzrok, values = ~stevilo.z,
              name = "ZS", 
              domain = list(row = 1, column = 0)) %>% 
      add_pie(data = data2(), labels = ~vzrok, values = ~stevilo.v,
              name = "VS", 
              domain = list(row = 1, column = 1)) %>% 
      layout(title = "", showlegend = T, grid=list(rows=2, columns=2),
             xaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             legend = list(x = 0, y = -0.1, orientation = "h"),
             width = 550, height = 450) %>%
      add_annotations(x=c(-0.85, 0.2), y=1.07, text = c("Zahodna Slovenija", "Vzhodna Slovenija"), 
                      xref = "paper", yref = "paper", xanchor = "left", showarrow = FALSE)
  ))
}

shinyApp(ui,server)
```